"""
Report Generator - Creates PDF and Markdown reports from incident brief
"""

import io
import markdown
from datetime import datetime
from typing import Dict, Any, List
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import logging

logger = logging.getLogger(__name__)


class ReportGenerator:
    """
    Generate PDF and Markdown reports from incident brief data.
    """
    
    def __init__(self):
        self.styles = getSampleStyleSheet()
        # Add custom styles
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=30
        ))
        self.styles.add(ParagraphStyle(
            name='ErrorStyle',
            parent=self.styles['Normal'],
            textColor=colors.HexColor('#dc2626'),
            backColor=colors.HexColor('#fee2e2'),
            borderPadding=5,
            borderRadius=5
        ))
    
    def generate_markdown(self, brief: Dict[str, Any]) -> str:
        """
        Generate Markdown report from incident brief.
        """
        markdown_content = f"""# 🚨 Incident Brief Report

## Incident Details
| Field | Value |
|-------|-------|
| **Request ID** | {brief.get('request_id', 'N/A')} |
| **Time Range** | {brief.get('time_range', 'N/A')} |
| **Environment** | {brief.get('environment', 'N/A')} |
| **Generated** | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |

---

## 📋 Summary

{brief.get('summary', 'No summary available')}

---

## ❌ Errors Found ({len(brief.get('errors_found', []))})

"""
        
        for error in brief.get('errors_found', []):
            markdown_content += f"""
### Error
- **Message:** {error.get('message', 'N/A')}
- **Time:** {error.get('timestamp', 'N/A')}
- **Service:** {error.get('service', 'N/A')}
- **Level:** {error.get('level', 'N/A')}
"""
            if error.get('stack_trace'):
                markdown_content += f"""
<details>
<summary>Stack Trace</summary>

{error.get('stack_trace')}

</details>
"""
        
        markdown_content += f"""
---

## 📅 Timeline ({brief.get('total_logs', 0)} events)

| Time | Level | Message | Service |
|------|-------|---------|---------|
"""
        
        for event in brief.get('timeline', []):
            markdown_content += f"| {event.get('timestamp', 'N/A')} | {event.get('level', 'N/A')} | {event.get('message', 'N/A')[:50]} | {event.get('service', 'N/A')} |\n"
        
        markdown_content += f"""
---

## 💡 Suggested Next Steps

"""
        for step in brief.get('suggested_next_steps', []):
            markdown_content += f"- {step}\n"
        
        markdown_content += f"""
---

## ℹ️ Additional Information

{brief.get('message', 'No additional information')}

---
*Report generated by Incident Brief Generator*
"""
        
        return markdown_content
    
    def generate_pdf(self, brief: Dict[str, Any]) -> bytes:
        """
        Generate PDF report from incident brief.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=72
        )
        
        story = []
        
        # Title
        title = Paragraph("🚨 Incident Brief Report", self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 0.2 * inch))
        
        # Incident Details Table
        details_data = [
            ["Request ID:", brief.get('request_id', 'N/A')],
            ["Time Range:", brief.get('time_range', 'N/A')],
            ["Environment:", brief.get('environment', 'N/A')],
            ["Generated:", datetime.now().strftime('%Y-%m-%d %H:%M:%S')]
        ]
        
        details_table = Table(details_data, colWidths=[1.5 * inch, 4 * inch])
        details_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#667eea')),
            ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(details_table)
        story.append(Spacer(1, 0.3 * inch))
        
        # Summary
        story.append(Paragraph("📋 Summary", self.styles['Heading2']))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(brief.get('summary', 'No summary available'), self.styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Errors Found
        errors = brief.get('errors_found', [])
        story.append(Paragraph(f"❌ Errors Found ({len(errors)})", self.styles['Heading2']))
        story.append(Spacer(1, 0.1 * inch))
        
        for error in errors:
            error_text = f"<b>Message:</b> {error.get('message', 'N/A')}<br/>"
            error_text += f"<b>Time:</b> {error.get('timestamp', 'N/A')}<br/>"
            error_text += f"<b>Service:</b> {error.get('service', 'N/A')}<br/>"
            error_text += f"<b>Level:</b> {error.get('level', 'N/A')}"
            
            story.append(Paragraph(error_text, self.styles['ErrorStyle']))
            if error.get('stack_trace'):
                story.append(Paragraph(f"<b>Stack Trace:</b><br/>{error.get('stack_trace')}", self.styles['Code']))
            story.append(Spacer(1, 0.1 * inch))
        
        story.append(Spacer(1, 0.2 * inch))
        
        # Timeline
        story.append(Paragraph(f"📅 Timeline ({brief.get('total_logs', 0)} events)", self.styles['Heading2']))
        story.append(Spacer(1, 0.1 * inch))
        
        timeline_data = [["Time", "Level", "Message", "Service"]]
        for event in brief.get('timeline', [])[:20]:  # Limit to 20 events
            timeline_data.append([
                event.get('timestamp', 'N/A')[:19],
                event.get('level', 'N/A'),
                event.get('message', 'N/A')[:60],
                event.get('service', 'N/A')
            ])
        
        timeline_table = Table(timeline_data, colWidths=[1.5 * inch, 0.8 * inch, 3 * inch, 1 * inch])
        timeline_table.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#667eea')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -2), 0.5, colors.grey),
        ]))
        story.append(timeline_table)
        story.append(Spacer(1, 0.2 * inch))
        
        # Suggested Next Steps
        story.append(Paragraph("💡 Suggested Next Steps", self.styles['Heading2']))
        story.append(Spacer(1, 0.1 * inch))
        
        for step in brief.get('suggested_next_steps', []):
            story.append(Paragraph(f"• {step}", self.styles['Normal']))
            story.append(Spacer(1, 0.05 * inch))
        
        story.append(Spacer(1, 0.2 * inch))
        
        # Additional Info
        story.append(Paragraph("ℹ️ Additional Information", self.styles['Heading2']))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph(brief.get('message', 'No additional information'), self.styles['Normal']))
        story.append(Spacer(1, 0.2 * inch))
        
        # Footer
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#667eea')))
        story.append(Spacer(1, 0.1 * inch))
        story.append(Paragraph("Report generated by Incident Brief Generator", self.styles['Italic']))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer.getvalue()


# Singleton instance
report_generator = ReportGenerator()